travis:
  secure:
    BINSTAR_TOKEN: xZNhTx4GLakyzn2dTHdEAauvgitiIuQMJi5ul8uGnKk2sEVIaUEtKSI1VNRAWIcVrTq6Lamz+kTpAJvd8JvM6qfRIfIPBX27495l667pVZQvjU2dbwI/EUDCQhv1kC+823Ufv2KECg7MKSrETj05eeGawokjFDDOy+qhJbGzcNUHMY4yghqgTyAxco/ND20A7NwrRGVL8mrCHO+KIyoaeoslprc2rWyggPBcT2elSuDzAUJ6tZUq2P4JtibDncbWNXl/OxpcSyrSQdd4DS9p08xyCuJ5TmHuQguIdXSgzULIZv9rUfmUXaW4yyywhQAW2M4C+odPGN7u5obOrpqRXmOpSgezbDsp59zJ5fZTgEm4KxOQ/PGijpAVf4u17WO2LgjfR2FnM1SsC0pRz8cC/+EDafbytWFTg+D2kWGlFeqtR1Mgq+I2wfaB7gXUy3qcVNhF3f7/Ig8UHNYtDoXWzvn4Ox5cqMxuzThksRqmp6VMMcNO/HdJwxqsG2rYmr0qlnx/SxVeZJstzsZFqaJWpgB2fq9BwbDkm9YvRM2362vF3dWNxTPIYZwe109/N/8HeDOCbeAdPkQORD0AqfCHMbOfYVSDiBso5c77qj0jlSanGGEll47eeWR5gE0cfqLds+SLyoK/+ASJpkTBvBmeVV4pmGTejRsu4QemRAmzy4o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
